import * as vscode from 'vscode';
import * as path from 'path';
import { load, type Cheerio } from 'cheerio';
import type { Element } from 'domhandler';
import fetch from 'node-fetch';

export interface SaveOptions {
    showDialog: boolean;
    showNotifications: boolean;
    embedWebResources: boolean;
}

export async function renderAndSave(context: vscode.ExtensionContext, document: vscode.TextDocument, options: SaveOptions) {
    const config = vscode.workspace.getConfiguration('freeze-markdown', document.uri);

    const process = async (progress?: vscode.Progress<{ message?: string; increment?: number }>) => {
        try {
            progress?.report({ increment: 20, message: "Rendering Markdown..." });
            const renderOutput = await vscode.commands.executeCommand<string>(
                'markdown.api.render',
                document.getText()
            );

            if (typeof renderOutput !== 'string') {
                throw new Error('Markdown renderer did not return a string.');
            }

            progress?.report({ increment: 30, message: "Constructing full HTML..." });
            const fullHtml = await generateFullHtml(context, renderOutput, document.uri);

            // *** THE FIX IS HERE ***
            // Check the new setting OR if we are in development mode.
            const createDebugFile = config.get('createDebugFile', false);
            if (context.extensionMode === vscode.ExtensionMode.Development || createDebugFile) {
                const debugSavePath = vscode.Uri.file(document.uri.fsPath + '.debug.html');
                await vscode.workspace.fs.writeFile(debugSavePath, Buffer.from(fullHtml, 'utf8'));
            }

            progress?.report({ increment: 30, message: "Embedding local resources..." });
            const selfContainedHtml = await embedResources(fullHtml, document.uri, options.embedWebResources);
            
            const outputSuffix = config.get('outputSuffix', '.html');
            const finalSavePath = document.uri.fsPath.replace(/\.md$/, '') + outputSuffix;

            let saveUri: vscode.Uri | undefined;
            if (options.showDialog) {
                progress?.report({ increment: 10, message: "Prompting for save location..." });
                saveUri = await vscode.window.showSaveDialog({ 
                    defaultUri: vscode.Uri.file(finalSavePath), 
                    filters: { 'HTML Files': ['html'] } 
                });
            } else {
                saveUri = vscode.Uri.file(finalSavePath);
            }

            if (saveUri) {
                await vscode.workspace.fs.writeFile(saveUri, Buffer.from(selfContainedHtml, 'utf8'));
                if (options.showNotifications) {
                    vscode.window.showInformationMessage(`MD Successfully exported to: ${saveUri.fsPath}`);
                }
            }
        } catch (e: any) {
            vscode.window.showErrorMessage(`Export failed: ${e.message}`);
        }
    };

    if (options.showNotifications) {
        await vscode.window.withProgress({
            location: vscode.ProgressLocation.Notification,
            title: 'Exporting HTML...',
            cancellable: false
        }, process);
    } else {
        await process();
    }
}


// --- All other helper functions below are unchanged ---

async function getTemplate(context: vscode.ExtensionContext, documentUri: vscode.Uri): Promise<string> {
    const workspaceFolder = vscode.workspace.getWorkspaceFolder(documentUri);
    if (workspaceFolder) {
        const workspaceTemplateUri = vscode.Uri.joinPath(workspaceFolder.uri, '.vscode', 'freeze-markdown-template.html');
        try {
            const content = await vscode.workspace.fs.readFile(workspaceTemplateUri);
            return content.toString();
        } catch (error) {
            const defaultTemplateUri = vscode.Uri.joinPath(context.extensionUri, 'media', 'template.html');
            const defaultContent = await vscode.workspace.fs.readFile(defaultTemplateUri);
            await vscode.workspace.fs.writeFile(workspaceTemplateUri, defaultContent);
            vscode.window.showInformationMessage(`Created a customizable HTML template at .vscode/freeze-markdown-template.html`);
            return defaultContent.toString();
        }
    }
    
    const defaultTemplateUri = vscode.Uri.joinPath(context.extensionUri, 'media', 'template.html');
    const defaultContent = await vscode.workspace.fs.readFile(defaultTemplateUri);
    return defaultContent.toString();
}

/**
 * Constructs a complete HTML document from a rendered Markdown snippet.
 * 
 * This function takes the HTML fragment generated by VS Code's Markdown renderer
 * and combines it with a template. It performs several key tasks:
 * 1. Loads a base HTML template (either a default one or a user-provided one).
 * 2. Extracts the body content and any scripts from the rendered Markdown HTML.
 * 3. Intelligently determines a document title from headings (h1, h2, h3) or the first paragraph.
 * 4. Injects the body content, title, and scripts into the template.
 * 5. Gathers and includes links to VS Code's default Markdown preview stylesheets and user-defined stylesheets.
 * 6. Sets a 'vscode-dark' or 'vscode-light' class on the body based on the current theme.
 * 7. Injects editor font settings as CSS variables.
 * 
 * @param context The extension context.
 * @param renderOutput The HTML string produced by the `markdown.api.render` command.
 * @param documentUri The URI of the source Markdown document.
 * @returns A promise that resolves to the complete HTML string, ready for resource embedding.
 */
async function generateFullHtml(context: vscode.ExtensionContext, renderOutput: string, documentUri: vscode.Uri): Promise<string> {
    let templateHtml = await getTemplate(context, documentUri);
    const $rendered = load(renderOutput);
    
    const bodyContent = $rendered.html(); 
    const scripts = $rendered('script').toArray().map(el => load(el).html()).join('\n');
    
    // --- START: Improved Title Logic with Debugging ---
    let title = '';
    let titleDebugInfo = '<!-- Title Debug Info: ';

    try {
        const h1 = $rendered('h1').first().text();
        const h2 = $rendered('h2').first().text();
        const h3 = $rendered('h3').first().text();
        const p = $rendered('p').first().text();

        title = h1 || h2 || h3 || '';
        titleDebugInfo += `H1: '${h1}', H2: '${h2}', H3: '${h3}', P: '${p.substring(0, 20)}...'`;

        if (!title && p) {
            title = p.split(/[.!?]/)[0];
            if (title.length > 80) {
                title = title.substring(0, 80).trim() + '…';
            }
        }

        if (!title) {
            title = path.basename(documentUri.fsPath, '.md');
            titleDebugInfo += ` | Fell back to filename.`;
        }

        titleDebugInfo += ' -->';
    } catch (e: any) {
        title = path.basename(documentUri.fsPath, '.md');
        titleDebugInfo += ` | ERROR during title extraction: ${e.message} -->`;
    }
    
    // Inject the title and the debug info
    templateHtml = templateHtml.replace('<!-- TITLE_PLACEHOLDER -->', title.trim());
    templateHtml = templateHtml.replace('<!-- BODY_PLACEHOLDER -->', bodyContent + '\n' + titleDebugInfo);
    // --- END: Improved Title Logic with Debugging ---

    const { styles: defaultStyles, variables: styleVarsFromConfig } = await getDefaultStylesFromConfig(context, documentUri);
    const userStyleLinks = getUserStyles(documentUri);

    const theme = vscode.window.activeColorTheme;
    const bodyClass = theme.kind === vscode.ColorThemeKind.Dark ? 'vscode-dark' : 'vscode-light';

    let styleVariables;
    if (styleVarsFromConfig) {
        styleVariables = styleVarsFromConfig;
    } else {
        const editorConfig = vscode.workspace.getConfiguration('editor', documentUri);
        styleVariables = `--vscode-editor-font-family: ${editorConfig.get('fontFamily', 'sans-serif')};`;
    }

    templateHtml = templateHtml.replace('<!-- DEFAULT_STYLES_PLACEHOLDER -->', defaultStyles);
    templateHtml = templateHtml.replace('<!-- USER_STYLES_PLACEHOLDER -->', userStyleLinks + scripts);
    templateHtml = templateHtml.replace('<!-- BODY_CLASS -->', bodyClass);
    templateHtml = templateHtml.replace('<!-- STYLE_VARIABLES -->', styleVariables);
    
    return templateHtml;
}

async function getDefaultStylesFromConfig(context: vscode.ExtensionContext, documentUri: vscode.Uri): Promise<{ styles: string, variables: string }> {
    const workspaceFolder = vscode.workspace.getWorkspaceFolder(documentUri);

    let stylesJsonContent: string;

    if (workspaceFolder) {
        const stylesJsonUri = vscode.Uri.joinPath(workspaceFolder.uri, '.vscode', 'freeze-markdown-styles.json');
        try {
            const content = await vscode.workspace.fs.readFile(stylesJsonUri);
            stylesJsonContent = content.toString();
        } catch (error) {
            const defaultStylesUri = vscode.Uri.joinPath(context.extensionUri, 'media', 'default-styles.json');
            const defaultContent = await vscode.workspace.fs.readFile(defaultStylesUri);
            await vscode.workspace.fs.writeFile(stylesJsonUri, defaultContent);
            vscode.window.showInformationMessage(`Created a customizable styles file at .vscode/freeze-markdown-styles.json. Run 'Update Markdown Preview Theme Styles' to populate it.`);
            stylesJsonContent = defaultContent.toString();
        }
    } else {
        const defaultStylesUri = vscode.Uri.joinPath(context.extensionUri, 'media', 'default-styles.json');
        const defaultContent = await vscode.workspace.fs.readFile(defaultStylesUri);
        stylesJsonContent = defaultContent.toString();
    }

    try {
        const stylesConfig = JSON.parse(stylesJsonContent);
        if (stylesConfig.styles && Array.isArray(stylesConfig.styles)) {
            const styleContents = stylesConfig.styles.map((style: { content: string }) => style.content).join('\n\n/* --- STYLE SEPARATOR --- */\n\n');
            return {
                styles: `<style data-source="freeze-markdown-styles.json">\n${styleContents}\n</style>`,
                variables: ''
            };
        } else if (stylesConfig.styles && typeof stylesConfig.styles === 'string') {
            return { styles: '', variables: stylesConfig.styles };
        }
    } catch (e: any) {
        console.error('Error parsing freeze-markdown-styles.json', e);
        vscode.window.showErrorMessage(`Error parsing .vscode/freeze-markdown-styles.json: ${e.message}. Please check its format or run the update command.`);
    }

    return { styles: '', variables: '' };
}

function getUserStyles(documentUri: vscode.Uri): string {
    const markdownStyles = vscode.workspace.getConfiguration('markdown', documentUri).get<string[]>('styles', []);
    const workspaceFolder = vscode.workspace.getWorkspaceFolder(documentUri);
    if (workspaceFolder) {
        return markdownStyles.map(stylePath => {
            const styleUri = vscode.Uri.joinPath(workspaceFolder.uri, stylePath);
            return `<link rel="stylesheet" href="${styleUri.toString()}" type="text/css" media="screen">`;
        }).join('\n');
    }
    return '';
}

async function embedResources(html: string, sourceUri: vscode.Uri, embedWeb: boolean): Promise<string> {
    const $ = load(html);
    const promises: Promise<void>[] = [];
    const sourceDir = vscode.Uri.file(path.dirname(sourceUri.fsPath));

    $('link[rel="stylesheet"]').each((_i, el) => {
        const link = $(el);
        const href = link.attr('href');
        if (href) promises.push(resolveAndEmbedCss(href, link));
    });

    $('img').each((_i, el) => {
        const img = $(el);
        const src = img.attr('src');
        if (src && !src.startsWith('data:')) {
            if (!src.startsWith('http') || embedWeb) {
                promises.push(resolveAndEmbedImage(src, img, sourceDir));
            }
        }
    });

    $('script[src]').each((_i, el) => {
        const script = $(el);
        const src = script.attr('src');
        if (src && (src.startsWith('http:') || src.startsWith('https:')) && embedWeb) {
            promises.push(resolveAndEmbedScript(src, script));
        }
    });

    await Promise.all(promises);
    return $.html();
}

async function resolveAndEmbedScript(src: string, scriptElement: Cheerio<Element>) {
    try {
        const response = await fetch(src);
        if (!response.ok) throw new Error(`Failed to fetch script: ${response.statusText}`);
        const scriptContent = await response.text();
        scriptElement.removeAttr('src').text(scriptContent);
    } catch (e) {
        console.error(`Failed to embed script: ${src}`, e);
        scriptElement.remove();
    }
}

async function resolveAndEmbedCss(href: string, linkElement: Cheerio<Element>) {
    try {
        let fileUri = vscode.Uri.parse(href, true);
        if (fileUri.scheme === 'vscode-resource') {
            fileUri = vscode.Uri.file(fileUri.fsPath);
        }
        const content = await vscode.workspace.fs.readFile(fileUri);
        linkElement.replaceWith(`<style data-embedded-from="${href}">\n${content.toString()}\n</style>`);
    } catch (e) { console.error(`Failed to embed CSS: ${href}`, e); }
}

async function resolveAndEmbedImage(src: string, imgElement: Cheerio<Element>, baseUri: vscode.Uri) {
    try {
        let fileUri: vscode.Uri;
        if (src.startsWith('http')) {
            const response = await fetch(src);
            if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);
            const buffer = await response.buffer();
            const mimeType = response.headers.get('content-type') || 'application/octet-stream';
            const base64 = buffer.toString('base64');
            imgElement.attr('src', `data:${mimeType};base64,${base64}`);
            return;
        }
        
        if (src.startsWith('vscode-resource:')) {
            const tempUri = vscode.Uri.parse(src, true);
            fileUri = vscode.Uri.file(tempUri.fsPath);
        } else if (path.isAbsolute(src)) {
            fileUri = vscode.Uri.file(src);
        } else {
            fileUri = vscode.Uri.joinPath(baseUri, src);
        }
        
        const content = await vscode.workspace.fs.readFile(fileUri);
        const ext = path.extname(fileUri.fsPath).substring(1).toLowerCase();
        const mimeType = getMimeType(ext);
        const base64 = Buffer.from(content).toString('base64');
        imgElement.attr('src', `data:${mimeType};base64,${base64}`);
    } catch (e) {
        console.error(`Failed to embed image: ${src}`, e);
    }
}

function getMimeType(extension: string): string {
    const mimes: { [key: string]: string } = {
        'jpg': 'image/jpeg', 'jpeg': 'image/jpeg', 'png': 'image/png',
        'gif': 'image/gif', 'svg': 'image/svg+xml', 'webp': 'image/webp',
    };
    return mimes[extension] || 'application/octet-stream';
}
